-- --------------------------------------------------------
-- Host:                         rr-websites.nl
-- Server versie:                10.0.24-MariaDB - MariaDB Server
-- Server OS:                    Linux
-- HeidiSQL Versie:              9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Databasestructuur van recipe_app wordt geschreven
CREATE DATABASE IF NOT EXISTS `recipe_app` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `recipe_app`;


-- Structuur van  tabel recipe_app.categories wordt geschreven
CREATE TABLE IF NOT EXISTS `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

-- Dumpen data van tabel recipe_app.categories: ~5 rows (ongeveer)
/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT INTO `categories` (`id`, `name`) VALUES
	(1, 'Voorgerechten'),
	(2, 'Hoofdgerechten'),
	(3, 'Nagerechten'),
	(4, 'Tussengerechten'),
	(5, 'Cake, gebak en taart'),
	(6, 'Overig');
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;



-- Structuur van  tabel rrwebsites_recipe_app.favorieten wordt geschreven
CREATE TABLE IF NOT EXISTS `favorites` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL DEFAULT '0',
  `recipe_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=latin1;

-- Dumpen data van tabel recipe_app.favorites: ~3 rows (ongeveer)
/*!40000 ALTER TABLE `favorites` DISABLE KEYS */;
INSERT INTO `favorites` (`id`, `user_id`, `recipe_id`) VALUES
	(9, 23, 17),
	(10, 23, 30),
	(11, 23, 28);
/*!40000 ALTER TABLE `favorites` ENABLE KEYS */;


-- Structuur van  tabel recipe_app.recipes wordt geschreven
CREATE TABLE IF NOT EXISTS `recipes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category_id` int(11) NOT NULL DEFAULT '0',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` int(11) NOT NULL DEFAULT '0',
  `title` varchar(50) NOT NULL DEFAULT '0',
  `description` text NOT NULL,
  `ingredients` text NOT NULL,
  `picture_url` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=113 DEFAULT CHARSET=latin1;

-- Dumpen data van tabel recipe_app.recipes: ~18 rows (ongeveer)
/*!40000 ALTER TABLE `recipes` DISABLE KEYS */;
INSERT INTO `recipes` (`id`, `category_id`, `updated_at`, `created_at`, `user_id`, `title`, `description`, `ingredients`, `picture_url`) VALUES
	(44, 6, '2016-06-08 07:24:55', '0000-00-00 00:00:00', 27, 'Witte broodjes', 'Bereidingswijze\r\nVoorbereiding: 2uur  ›  Bereiding: 20min  ›  Klaar in:2uur20min \r\nMeng water, gist en suiker in een grote kom. Laat ongeveer 10 minuten staan, tot het schuimig wordt.\r\nVoeg olie, zout en bijna de helft van de bloem toe aan het gistmengsel. Meng door en meng vervolgens beetje bij beetje de resterende bloem erdoor tot het deeg van de kom loslaat. Leg op een licht bebloemd oppervlak en kneed tot een glad en elastisch deeg, in ongeveer 8 minuten.\r\nVet een grote kom licht in met olie en leg het deeg in de kom, beweeg rond om met olie te bedekken. Dek af met een schone, vochtige theedoek en laat op een warme plaats 1 uur rijzen tot het deeg in volume is verdubbeld.\r\nDruk de lucht uit het deeg en leg op een licht bebloemd oppervlak. Verdeel het deeg in 16 gelijke stukken en vorm hier ronde balletjes van. Leg ze minstens 5 cm van elkaar af op een ingevette bakplaat. Dek af met een vochtige doek en laat ze nog eens 40 minuten rijzen, tot ze in volume verdubbeld zijn.\r\nVerhit ondertussen de oven voor op 200°C.\r\nBak de broodjes in 18-20 minuten goudbruin in de voorverwarmde oven.', '350 ml warm water 1 eetlepel droge gist 2 eetlepels suiker 2 eetlepels plantaardige olie (bijv. zonnebloemolie) 1 theelepel zout 500 gr tarwebloem (voor witbrood)', '73676.jpg'),
	(45, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Champignonsoep', 'Bereidingswijze\r\nDe soep is gebonden op basis van een blanke roux. Roux is een mengsel van gelijke delen boter en bloem. Om soep te binden heb je minimaal 30 gram bloem en 30 gram boer nodig. Wil je een stevigere soep, gebruik dan 50 gram van beide ingredienten.\r\n\r\nSnipper de ui heel fijn en pers de teen knoflook uit. Smelt de klont boter in de soeppan op een rustig vuur.\r\n\r\nLaat de boter niet kleuren. Fruit de ui en doe de knoflook erbij.\r\nLaat de ui niet bruin worden, maar bak deze glazig. Doe de bloem in een keer in de pan en roer deze met een houten spatel door de boter en massa tot er een soort deeg is. Roer even goed door: je wilt geen klonten. Voeg nu langzaam de melk toe, terwijl je blijft roeren.\r\n\r\nVoeg vervolgens de champignons toe en breng het mengsel rustig aan de kook. Voeg vervolgens de kippenbouillon toe.\r\n\r\nBlijf de champignonsoep de hele tijd goed roeren. Melk brandt nou eenmaal snel aan en daar word je soep niet beter op.\r\n\r\nHak wat bladpeterselie heel erg fijn met je koksmes. Doe ca. 2 lepels vlak voor het opdienen door je zelfgemaakte soep, samen met een flinke scheut witte wijn.\r\nBreng de soep op smaak met peper en eventueel wat zout.', '* 250 gram champignons * 5 dl kippenbouillon * 5 dl volle melk * 1 ui * 2 eetlepels fijngehakte bladpeterselie * 30 gram boter * 30 gram bloem * 1 flinke scheut fruitige, droge witte wijn * 1 teentje knoflook * witte peper', '44517.jpg'),
	(46, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Traditionele uiensoep!', 'Bereidingswijze\r\nSmelt de boter in een pan met dikke bodem en voeg de ui toe. Bak de ui op laag vuur onder af en toe roeren 25 minuten, of totdat de uien diep goudbruin zijn en beginnen te karameliseren.\r\nVoeg de knoflook en de bloem toe en blijf 2 minuten roeren. Voeg nu langzaam en al roerend de bouillon en de wijn toe en breng aan de kook. Voeg het laurierblad en de takjes tijm toe en breng op smaak met zout en peper. Doe een deksel op de pan en laat 25 minuten zachtjes pruttelen. Verwijder het laurierblad en de takjes tijm en proef of de soep goed van smaak is. Verwarm de grill voor.\r\nRooster de sneetjes stokbrood, verdeel ze over de 6 soepkommen en schep de soep erover. Bestrooi met geraspte Gruyere kaas en zet de soep onder de grill tot de kaas goudbruin en gesmolten is. Dien onmiddellijk op.', '50 gr boter 750 gr uien,Ui in dunne ringen gesneden 2 tenen knoflook 45 gr bloem 2 liter runder-of kippenbouillon 250 ml droge witte of rode wijn 1 laurierblad 2 takjes tijm zout en peper 12 sneetjes stokbrood 100 gr Gruyerekaas, geraspt', '81749.jpg'),
	(71, 2, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Amuse van zalmrolletjes gevuld met spinazie en bou', '100 gr gerookte zalm\r\nklein handje spinazieblaadjes\r\nhalf pakje Boursin\r\nbeetjes bieslook fijngeknipt.\r\n2 el creme fraiche', 'Bereidingswijze Meng een Boursin 2 lepels creme frache en wat bieslooksnipper tot een smeuige, homogene mengeling. Leg de plakjes zalm uit en leg er wat blaadjes spinazie in. Leg nu de mengeling van de Boursin er op. Rol de zalm op met behulp van bakpapier en leg de rollen, gewikkeld in het papier, enkele uren in de diepvriezer. Even voor het serveren haalt u de rollade uit de diepvriezer en snijdt u er kleine rondjes van. Leg de hapjes op een schotel en versier met enkele snippers sinaasappelschil of wat bierslook', '51036.jpg'),
	(72, 2, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Griekse Pita met gyros en tzatziki', 'Voorbereiding\r\nHet vlees of de kip marineren kan je het beste natuurlijk een dag van tevoren doen en dit lekker laten intrekken in de koelkast. \r\nMeng voor de marinade de olijfolie, het citroensap, de knoflook, versgemalen peper, zout, oregano, dille, paprikapoeder en cayennepeper goed door elkaar. Voeg het vlees of de kipfilet toe en laat dit goed intrekken (liefst dus een dag van tevoren)\r\nBereidingswijze\r\n\r\nMaak eerst de pitabroodjes:\r\n\r\nDe gist verbrokkelen en met het water glad roeren\r\n\r\nDe overige ingredienten toevoegen en tot een glad soepel deeg kneden\r\n\r\nDaarna 30 minuten op een warme plaats, afgedekt, laten rijzen\r\n\r\nHet deeg op een met bloem bestoven aanrecht nogmaals kneden\r\n\r\nIn gelijke porties verdelen en elk stuk uitrollen tot een circel van ongeveer 18 cm\r\n\r\nOp 2 met bakpapier bedekte bakblikken leggen en met een vork een aantal keren inprikken\r\n\r\nAfdekken en nog ongeveer 15 minuten laten rijzen\r\n\r\nOven ondertussen voorverwarmen op 180 graden\r\n\r\nDe broodjes met water bestrijken en licht met roggemeel bestuiven\r\n\r\nDe pitabroodjes op de bakblikken na elkaar op een rooster in het midden van de oven in 15 minuten gaar bakken\r\n\r\nOnder een doek laten afkoelen\r\n\r\n\r\nMaak dan de tzaziki\r\n\r\nKomkommer schillen, raspen en door de yoghurt mengen\r\n\r\nTeentjes knoflook persen en samen met de azijn toevoegen aan de yoghurt\r\n\r\nGoed roeren en op smaak brengen met peper en zout\r\n\r\n\r\nMaak ten slotte de gyros:\r\n\r\nHaal het gemarineerde vlees uit de koelkast\r\n\r\nGrill het op de BBQ in ongeveer 8 minuten gaar en bruin (besrijk tussendoor met de marinade)\r\n\r\nSnijd het vlees in dunne plakjes\r\n\r\nDoe de gyros in de pitabroodjes met wat sla en dunne reepjes ui. Tzaziki erop en klaar\r\n\r\nServeertips\r\nJe kan dit serveren met een lekkere Griekse salade en een goed glaasje witte wijn.', 'Pitabroodjes  20 gram gist (van de bakker) 1/4 liter water 1 tl zout snufje suiker 8 el olijfolie 500 gram roggebloem  Gyros  600 gram mager varkensvlees of kipfilet olijfolie citroensap 2 teentjes knoflook, geperst zout gemalen peper oregano klein beetje dille paprikapoeder cayennepeper  Tzaziki  1/2 liter dikke yoghurt 1 kleine komkommer 3 teentjes knoflook 2 el azijn peper en zout', '31062.jpg'),
	(73, 2, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Kip Stroganoff', 'Bereidingswijze\r\nSnij de kipfilet in niet te kleine stukken. Doe de boter en de olie in de pan en bak de kipfilet rondom bruin. Neem het vlees uit de pan en houd het warm.\r\nBak de spekjes in het overgebleven vet lichtbruin. Voeg de ui, champignons, paprika en knoflook toe en laat even meebakken. Voeg tomatenpuree, paprikapoeder, wodka en room toe.\r\nLaat dit op een laag vuur inkoken tot een dunne saus, breng op smaak met peper en zout en cayennepeper. Voeg de stukjes kipfilet toe en laat het samen even op temperatuur komen.', '4 halve kipfilets 50 gr boter en 1 el olie 1/2 rode paprika in stukjes 50 gr. gerookt spek in stukjes 1 kleine ui gesnipperd 125 gr champignons in plakjes 1 teentje knoflook gesnipperd klein blikje tomatenpuree 2 tl paprikapoeder 1 glaasje wodka 2 dl slagroom of koksroom (o.i.d.) Peper en zout Cayennepeper', '37464.jpg'),
	(74, 3, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Dame Blanche Deluxe', 'Een heel makkelijk toetje. Succes verzekerd. En toch net even anders.\r\nVoorbereiding\r\nDit hoeft niet maar is wel makkelijk met een etentje.Ik schep vantevoren ijsbollen (2 of 3 per persoon)leg ze op een met plasticfolie bekleede schaal en vries ze weer in. Het ijs kan dan kort voor het serveren in de coupes en smelt niet zo snel. Heb je plaats leg dan ook de ijscoupes vantevoren in de vriezer.\r\nBereidingswijze\r\nSmelt de marsrepen met 2,5dl slagroom au bain marie. Goed roeren tot je een mooie gladde saus krijgt. Klop de andere 2,5dl slagroom stijf en zet in de koelkast.\r\nVerkruimel de Maltesers (doe ze in een stevige plastic zak en sla er op met een deegroller ofzo) Doe 2 of 3 bollen ijs in een coupe, doe er de warme saus over en strooi er de verkruimelde Maltesers over.\r\nServeertips\r\nDe chocoladesaus die over is kan je in een sauskom op tafel zetten. De slagroom in een mooie schaal ernaast. Ik doe de slagroom nooit op het ijs. Veel mensen vinden het te zoet. Andere willen juist veel slagroom.', '2 bakken roomijs (goede kwaliteit) 2x2,5dl slagroom 2 grote marsrepen 1 zak maltesers (krokante chocoladekogels)', '21438.jpg'),
	(75, 3, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Cassata', 'Voorbereiding\r\nSnijd voor de Derde laag de kersen, abrikozen, ananas en groene kersen fijn. Klop de eiwitten met de mixer tot zich pieken vormen. Klop dan langzaam de suiker erbij. Schep hier de geklopte eiwitten luchtig door. Klop de room en amandelessence met de mixer tot er pieken vormen. Schep het eimengsel erdoor. Schenk het mengsel in een ronde vorm met een doorsnede van 20 cm. Strijk de bovenkant af en laat de inhoud bevriezen. Maak de Tweede laag : Klop de eiwitten met de mixer tot zich stevige pieken vormen. Klop dan langzaam de gezeefde poedersuiker erdoor. Klop deroom tot zich pieken vormen. Schep het eiwitmengsel erdoor. Doe de chocolade in een kommetje en roer de eierdooiers erdoor. Roer en mengsel van de cacao en water door het chocolademengsel. Roer het chocolademengsel door het roommengsel. Maak de Derde laag : Klop de room en vanille-essence met de mixer tot zich stevige pieken vormen. Klop het eiwit met de mixer tot zich zachte pieken vormen. Voeg langzaam de poedersuiker aan het eiwit toe en klop het goed na elke toevoeging. Roer het eiwitmengsel door de room. Roe het fruit en amandelen erdoor.\r\nBereidingswijze\r\nSpreid een tweede laag uit over de amandellaag. Laat deze bevriezen. Spreid een Derde laag uit over de tweede laag. Laat deze bevriezen. Ga met de spatel langs de rand van de cassata. Leg een warme doek over de onderkant en zijkanten. Keer de cassata op een schaal.', '2 eieren - 110 gram poedersuiker - 125 ml slagroom - enkele druppels amandelessence - Tweede laag : 2 gescheiden eieren - 110 gram poedersuiker - 125 ml slagroom - 60 gram gesmolten pure chocolade - 2 eetlepels cacaopoeder - 1 1/2 eetlepel water - Derde laag : 250 ml slagroom - 1 theelepel vanille-essence - 1 geklopt eiwit - 55 gram poedersuiker - 2 eetlepels rode geglaceerde kersen - 2 geglaceerde abrikozen - 2 geglaceerde ananasringen - 1 eetlepel geglaceerde groene kersen - 30 gram geschaafde amandelen', '53124.jpg'),
	(76, 3, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Crème Brulee', 'Bereidingswijze\r\n1. De melk met het vanillestokje en 20 gr suiker aan de kook brengen. 2. Klop in een kom de eidooiers met 60 gr suiker los. De hete melk al roerend toevoegen en vervolgens de slagroom erdoor roeren. 3. Vanillestokje opensnijden en de zaadjes eruit schrapen. Vanillezaadjes door het melkmengsel roeren en mengsel in ovenschaaltjes schenken. 4. Oven voorverwarmen op 120ºC. Schaaltjes in braadslede of bakplaat zetten en heet water in braadslede schenken tot iets onder rand van schaaltjes. Crème brulee in midden van oven in ongeveer 40 minuten laten stollen. 5. De grill voorverwarmen op hoogste stand. Op elke crème brulee 1 el rietsuiker strooien en suiker onder grill in enkele minuten laten caramelisseren.\r\nServeertips\r\nLekker met een bolletje vanille-ijs', '2 dl melk * 1 vanillestokje * 80 gr kristalsuiker * 5 eidooiers * 2,5 dl slagroom * 4 el rietsuiker', '93869.jpg'),
	(77, 1, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Knapperig Knoflookbrood', 'Voorbereiding\r\nVerhit de oven voor op 180 C. Meng knoflook en olie in een schaaltje. In een ander schaaltje de kruiden mengen met de kaas, goed mengen. \r\nHet brood insnijden, ongeveer 10 dikke plakken, niet helemaal insnijden. De snijkanten van het brood besmeren met knoflook olie, bestrooien met het kruiden mengsel. Het brood in aluminiumfolie wikkelen en afbakken in de oven, 10-15 minuten. Onmiddelijk serveren.\r\nBereidingswijze\r\nOm in te vriezen \r\nMaar inplaats van het brood te wikkelen in aluminium folie, in plastic wikkelen en invriezen. Om te bereiden, uit plastic folie halen en in aluminim folie afbakken in een voorverwarmde oven op 180 C, 25-30 minuten.', '1 grote baguette/ciabatta -  2 teentjes knoflook, gehakt/geperst -  2 eetl. olijfolie -  2 eetl. gehakte verse peterselie -  2 eetl. vers gehakte tijm of 2 theel. gedroogde -  2 eetl vers gehakte marjorein of 2 theel. gedroogde.  1/2 theel paprika poeder -  2 eetl. geraspte parmezaanse kaas.', '17729.jpg'),
	(78, 4, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Reebiefstuk', 'Voorbereiding\r\nBestrooi de biefstukjes met wat pepepr.Halveer de witlof in de lengte,snij de harde kern eruit en snijd ze in lucifer dunne reepjes.\r\nBereidingswijze\r\nVerhit 25 gr. boter en bak de biefstukjes 2-3 min per kant.Smelt intussen in andere pan d erest van de boter en roerbak de witlof met de tijm 2 min.Leg een nestje witlof op 4 warme borden en leg de biefstuk erop.Houd warm.Roer de fond en de slagroom door het bakvet van de biefstukjes en breng aan de kook.Voeg mosterd,zout en peper naar smaak toe. Roer de maizena met 2 eetl water glad en bind hiermee de saus.Schep wat van de saus bij de biefstuk en geef de rest er apart bij.', '4 reebiefstukjes,peper,1 grote of 2 kleine witlofstuikjes,35 gr. boter, 1 theel. verse tijm, 1 dl. wildfond(pot), 1 dl. slagroom, 1 eetl. mosterd, zout,1-2 eetl. maizena.', '81835.JPG'),
	(79, 4, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Frans kaasplankje', 'Geen idee welke Franse kazen je moet kiezen als nagerecht? Een handig hulpje is om drie kazen te kiezen in de kleuren va de Franse vlag: rood, wit, blauw. Een roodkorstkaas (meestal oranje van kleur), dan een wittekorstkaas en tot slot een pittige blauwaderkaas. Kazen worden altijd in volgorde van de zachte smaak naar de sterke smaak gegeten.\r\nBereidingswijze\r\nLeg van elke kaassoort per persoon een stukje op een bord of serveer de kazen op een houten plank en laat een ieder zelf stukjes er vanaf snijden.\r\nServeertips\r\nLekker met vers notenbrood.', 'Kies niet meer dan vijf soorten kaas en reken op in totaal 100 gram kaas per persoon.  Roodkorstkaas: Port Salut of chaumes grand caractère  Wittekorstkaas: brie of camembert  Blauwaderkaas: fourme d`Ambert of rochebaron.  Eventueel kun je nog een stukje (half)harde kaas als gruyère of emmentaler erbij doen.', '21921.jpg'),
	(80, 4, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Zalmmousse', 'Voorbereiding\r\nWeek de gelatine in koud water. Blikjes openmaken, sap bewaren. Evt. vel en graten verwijderen.\r\nBereidingswijze\r\nGiet 1 dl zalmsap in een pannetje. Mix de zalm, voeg mayonaise, creme, ketchup, mosterd en citroensap toe. Zout en peper naar smaak. Breng het zalmsap aan de kook, los er van het vuur af de goed uitgeknepen gelatine in op. Roer dit mengsel door de zalmmassa. Schenk de mousse in een met olie ingevette vorm en laat minstens 2 uur opstijven in de koelkast.Maak de zijkant een beetje los en stort op een mooi bord.\r\nServeertips\r\nLekker met een groene salade, asperges en toast.\r\nTIP: In éénpersoonsvormpjes ook leuk als voorgerecht. Wikkel er dan als garnering een reep gerookte zalm omheen, garneer o.a. met een schijfje citroen.', ' 2 blikjes (rode)zalm (ca 200 g), 125 g crème fraîche, 4 blaadjes gelatine, 3 eetlepels mayonaise, 1 eetlepel tomatenketchup, 1 theelepel mosterd, 1 eetlepel vers citroensap, peper, zout, olie om in te vetten', '75827.jpg'),
	(81, 5, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Stroopwafelcake', 'Bereidingswijze\r\nBeboter de cakevorm en bestrooi met bloem (of wat van het zelfr. bakmeel)\r\n\r\nMix de boter met de suiker, basterdsuiker en vanillesuiker tot een zachte smeuiige massa (plm. 5 minuten mixen).\r\nVoeg één voor één de eieren toe. Steeds ei toevoegen als het eerdere ei is opgenomen.\r\nMeng het zelfrijzend bakmeel met zout en kaneel door elkaar.\r\nSpatel dit voorzichtig door de ei/boter/suiker-massa. Liever niet mixen. Als je het erdoor spatelt wordt het deeg luchtiger.\r\nSpatel op het laatst de stukjes stroopwafel door het deeg.\r\nDoe het deeg in de cakevorm.\r\n\r\nZet de vorm met het deeg in het midden van de koude oven.\r\nZet de oven op 170 graden en bak de cake in plm. 70 minuten bruin en gaar.\r\nPrik voordat je de cake uit de oven haalt even met een breipen of satéprikker om te controleren of de cake echt gaar is. Zit hier geen deeg aan dan kun je de cake uit de oven halen.\r\nLaat de cake plm. 10 minuten in de vorm rusten en daarna uit de vorm op een rooster afkoelen.', '200 gram zachte boter + wat boter voor de vorm 150 gram suiker 50 gram bruine basterdsuiker 1 zakje vanillesuiker 4 eieren 200 gram zelfrijzend bakmeel + wat extra voor de vorm 1 theelepel kaneel 1 mespunt zout 200 gram stroopwafels in kleine stukjes', '99278.jpg'),
	(82, 5, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Brownies gevuld met witte en bruine chocoladestukj', 'Bereidingswijze\r\nSmelt de boter langzaam in een pannetje en laat wat afkoelen. \r\nKlop de eieren los en klop de basterdsuiker hier voorzichtig doorheen tot alle klontjes weg zijn. \r\nRoer de afgekoelde boter en de vanille-essence (vanille-aroma) erdoor. \r\nZeef het zout, de cacao en het bloem en schep dit voorzichtig door het eimengsel. \r\nNiet roeren en niet te lang anders wordt het een cake!\r\n\r\nVerwarm de oven voor op 170 graden. \r\nSchep de gehakte chocolade door het deeg. \r\nGiet het mengsel in de met bakpapier beklede bakvorm. \r\nZet de vorm in het midden van de voorverwarmde oven en bak 35-40 minuten. \r\nLaat de koek goed afkoelen.\r\nTil het gebak er met behulp van het bakpapier uit de vorm. \r\nTrek het papier eraf en snij de brownies in stukken.', ' 140 gram boter - 4 eieren - 340 gram lichtbruine basterdsuiker - flinke snuf zout -  1 theelepel vanille-essence = vanillearoma in van die kleine flesjes of vanillesuiker 75 gram cacaopoeder -  140 gram bloem -  150 gram grof gehakte stukjes chocolade (je kunt zelf bepalen of je witte en/of pure chocolade gebruikt. Ik gebruik van allebei 75 gram).', '70803.jpg'),
	(83, 5, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'Witte-chocoladecheesecake met aardbeien', 'Een heerlijke kwarktaart met de volle smaak van witte chocolade en frisse aardbeien\r\nVoorbereiding\r\n\r\nMaak de biscuitjes fijn met een deegroller of keukenmachine. Voeg de gesmolten boter toe.\r\nBekleed een springvorm van 22cm met bakpapier en schep het mengsel erin. Druk stevig aan en zet in de koelkast.\r\nBereidingswijze\r\nKlop de slagroom, roomkaas, mascarpone, suiker en vanille tot een glad mengsel. Voeg de gesmolten chocolade toe en klop weer door elkaar.\r\nSchep dit mengsel op de biscuitbodem en laat ten minste 4 uur of liefst een nacht opstijven in de koelkast. \r\nSchep vlak voor het serveren de aardbeien erover die je nog door honing heen kan scheppen en verdeel de aardbeien over de bovenkant van de taart.', '130 gram biscuitjes 65 gram boter, gesmolten 250 ml slagroom 250 gram roomkaas, op kamertemperatuur 250 gram mascarpone 65 gram suiker 1 tl vanille-aroma 500 gram witte chocolade, gesmolten 375 gram aardbeien, in plakjes', '63948.jpg'),
	(84, 6, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, 'DOCE DE TOMATE, tomaten jam', 'Bereidingswijze\r\n\r\nBegin met het pellen van de tomaten, verwijder de zaadjes en het kroontje. Vervolgens doe je alle ingrediënten in een redelijk formaat pan en laat je dit rustig even sudderen.\r\n\r\nBreng vervolgens het mengsel aan de kook. Kook dit langzaam tot het de gewenste dikte heeft. Je moet er voor zorgen dat de jam voldoende ingekookt is. Jam die niet voldoende ingekookt is blijft vloeibaar en te lang ingekookte jam kan gaan kristalliseren. Roer af en toe even in de pan zodat het niet aankoekt.\r\n\r\nOp dit punt kun je het met de staafmixer wat gladder maken (indien gewenst). Dit heeft puur met persoonlijke voorkeur te maken. De een doet het wel, de ander niet. Mocht je de staafmixer gebruiken, breng het mengsel dan daarna nog even weer aan de kook.\r\n\r\nLaat iets afkoelen en vul je gesteriliseerde potjes tot aan de rand. Veeg de buitenste randjes goed schoon. Sluit ze goed en draai de potten met de deksels naar beneden tot ze volledig afgekoeld zijn.', '2 kg rijpe tomaten 1 kg suiker 1 kaneelstokje citroen schil 2 kruidnagels', '46503.jpeg'),
	(85, 6, '0000-00-00 00:00:00', '0000-00-00 00:00:00', 27, '20 ml rabarbersiroop  30 ml gin (niet te kruidig) ', 'Bereidingswijze Shake siroop, gin en citroensap met ijsblokjes Schenk in champagneglas (zonder ijs) Schenk het witbier erbij. Serveertips Decoreer met krul citroenschil', '20 ml rabarbersiroop  30 ml gin (niet te kruidig) (of wodka?) 15 ml citroensap 40 ml witbier (BE+ER) IJsklontjes', '43839.jpg');
/*!40000 ALTER TABLE `recipes` ENABLE KEYS */;


-- Structuur van  tabel recipe_app.users wordt geschreven
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '0',
  `password` varchar(255) NOT NULL DEFAULT '0',
  `email` varchar(100) NOT NULL DEFAULT '0',
  `remember_token` varchar(255) DEFAULT '0',
  `created_at` date DEFAULT NULL,
  `updated_at` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=latin1;

-- Dumpen data van tabel rrwebsites_recepten.users: ~10 rows (ongeveer)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `name`, `password`, `email`, `remember_token`, `created_at`, `updated_at`) VALUES
	(26, 'test', '$2y$10$YvA85fSIyepbBBFyz.3UuuAaei97mmOhBdYXZMxiAxIz6X//Mkd.i', 'test@tester.nl', '9jYKqOhSTePECV7PIw0Ag6MgnYX9cdAM22BVVC7iUGSSx4C8LBCsJOKVN36a', '2016-06-02', '2016-06-06'),
	(27, 'regilio dielemans', '$2y$10$uz/KwvmydO50o7adW1k/yOKr8iA6fTNIvo0Hfi9aLO5LJ6Uwu5csa', 'regilio_dielemans@hotmail.com', 'jiNpbhsyI4dDHRBZgLFdFIjl2Rb3ttMnyfyUXXletJ7q7XuwzHHPp0xv5qEF', '2016-06-06', '2016-06-08'),
	(28, 'Rick Verheijen', '$2y$10$TmUyLHBcVc9XOPFrWVqjCOiw0zj/w2Opv93BtiO3DAq0pflc6dCSO', 'rickverheijen1@hotmail.com', 'WvMMyMciJXi3ypP2wY6JvgINz6kmEvLFRXOhLjLYP9Ge0OAo3AKnkCwibWZp', '2016-06-06', '2016-06-06'),
	(29, 'regilio', '$2y$10$fVYfzDPp0/oO75VW.wlNhOjuVJjxoxFPDj1cZzU.oWER2TQu2L2Vy', 'regilio@hotmail.com', 'I7XOOkIqzXiAv9mnJtqPyBbPJ2SjTbTIXiPnmFA5MDzKMNGrRx7nMYgw3AYC', '2016-06-08', '2016-06-09'),
	(30, 'Daniel van Bavel', '$2y$10$m0vZTsnUZa/PIEszXElNROTCoWpyHsBw7RHQfnb9wqlZK3ihfBPES', 'daniel@danielvanbavel.nl', 'RI6VnmXfdl0d79gPVd1hCGjRkrFr2wosj1Gzv8AVNgtsTmzbfXK46WewMnNV', '2016-06-08', '2016-06-08'),
	(31, 'jumbo', '$2y$10$7wgwA5h.JMbXy3wj9oBAruzwLsBFnVeTEENfFlUVovWTnp7A81Qqi', 'jumbo@water.nl', 'Us6FG6O2z33ATcURvQf0n5nb062mYZu5BxyK6OWV7CVQOKftV6q1cz7uEqU6', '2016-06-08', '2016-06-08'),
	(32, '', '$2y$10$jHyUNqX1ZtwXAz/MkMbckO/SFzgmDzAs0dMUhlU360oCmdlWUrBOy', 'asd@asd.nlasdsad', 'GB11JaLnfM9Ik77yJMquvZKYcT7nfLITaBRCIczXWyK2rkgeZwUSYw47i238', '2016-06-08', '2016-06-08'),
	(33, '', '$2y$10$IXqq/5aXCTHa7BDZaVLkeeyxi/5vC8ZBCGIHsu0nsYJKdo5/gaZ5G', 'cliffsestig@gmail.com', '0', '2016-06-08', '2016-06-08'),
	(34, 'sophie', '$2y$10$Rl/rlNTtZgoLMShV/F6bIOM.zkJDjHZLbnA4StCrp9EotvC/cfhs6', 'sophiewaelput@live.nl', 'e0fS0RQCUqFf3rvAhycAsNAQWCGgLLYQWyiMxt5tlrpQzGKGeFgwXeEruS42', '2016-06-08', '2016-06-08'),
	(35, '0', '$2y$10$/nY2SIA0ySPfzcOBUcFoaOYzcQ/3zO.B2FKzGDVgKlFz7NGJ7dhum', 'regilio1@hotmail.com', '0', '2016-06-09', '2016-06-09');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
